Matrix is a collection of vectors.

4.7 Matrix vector multiplication in NumPy

In [17]:
from numpy import array

In [18]:
# Basis matrix
basis = array(
    [[3, 0],
     [0, 2]]
)

In [19]:
# Declare vector v
v = array([1, 1])

In [22]:
# create a new vector
new_v = basis.dot(v)
new_v

array([3, 2])

Example 4-8. Separating the basis vectors and applying them as a transformation

In [23]:
i_hat = array([2, 0])
j_hat = array([0, 3])

In [24]:
# compose basis matrix using i-hat and j-hat
# also need to transpose rows into columns
basis = array([i_hat, j_hat]).transpose()

In [25]:
basis

array([[2, 0],
       [0, 3]])

In [26]:
# declare vector v
v = array([1, 1])

# create a nwe vector
new_v = basis.dot(v)

In [27]:
new_v

array([2, 3])

Example 4-11. Combining two transformations

In [29]:
# transformation 1
i_hat1 = array([0, 1])
j_hat1 = array([-1, 0])
transform1 = array([i_hat, j_hat]).transpose()

In [30]:
# Transformation 2
i_hat2 = array([1, 0])
j_hat2 = array([1, 1])
transform2 = array([i_hat2, j_hat2]).transpose()

In [31]:
# Combine transformation
combined = transform2 @ transform1
print("COMBINED MATRIX:\n {}".format(combined))

COMBINED MATRIX:
 [[ 1 -1]
 [ 1  0]]


In [32]:
v = array([1, 2])
combined.dot(v)

array([-1,  1])

In general, you want to prefer `matmul()` and its shorthand `@` to
combine matrices rather than the `dot()` operator in NumPy.

Example 4-12. Applying the transformations in reverse

In [33]:
# Combine transformation
combined = transform1 @ transform2
print("COMBINED MATRIX:\n {}".format(combined))

COMBINED MATRIX:
 [[ 0 -1]
 [ 1  1]]


In [34]:
combined.dot(v)

array([-2,  3])

Note that the order you apply each transformation matters! If we apply transfor
mation1 on transformation2, we get a different result of [-2, 3]. So matrix dot products are not commutative, meaning you cannot flip the order and expect the same result.

Determinants